const $=s=>document.querySelector(s);
const titles=['The evidence comes first','BM25: the power of matching words','Finding meaning with vectors','Two rankings, one better shortlist','Inside Redis hybrid search','Choose the right retrieval path','Follow the missing connection','Zoom out with GraphRAG','Check every claim with Self-RAG','Adapt the amount of retrieval','When the first search isn’t enough','Build your own RAG system'];
const short=['RAG foundations','BM25','Vector retrieval','Reciprocal Rank Fusion','Redis hybrid search','Routing','Graph expansion','Microsoft GraphRAG','Self-RAG','Adaptive-RAG','Recovery paths','Your capstone'];
const goals=['An answer can sound right and still lack evidence. Learn to tell the difference.','See how term frequency, document length, and rarity shape a lexical score.','Understand what nearest neighbors can—and cannot—tell you.','Combine lexical and semantic results without mixing incompatible scores.','Separate filtering, retrieval, and fusion in the search engine.','Decide when to search directly, follow relationships, or look across a corpus.','Discover the evidence your original question did not name.','Move between specific facts and themes across a whole collection.','Turn a fluent draft into a set of claims you can actually verify.','Choose the smallest retrieval strategy that can satisfy the question.','Identify the evidence gap, take a useful next step, and know when to stop.','Bring the stages together, measure the tradeoffs, and explain your choices.'];
const groups=['01 · FOUNDATIONS','02 · CANDIDATE GENERATION','03 · THE SEARCH ENGINE','04 · CONNECTED EVIDENCE','05 · ADAPTIVE RETRIEVAL','06 · PUT IT TOGETHER'];
const records=['On May 12, Harbor’s delivery was delayed because Dock 4 was unavailable. The report does not identify why.','Dock 4 was unavailable on May 12 because Crane 7 failed inspection.','Crane 7 failed its May 12 inspection because of a hydraulic leak.','Northstar Services supplied the replacement seal for Crane 7 on May 13.','On May 20, Harbor experienced another delivery delay because a truck arrived late.','An invoice dispute is a billing disagreement. Customers must report it within 30 days.','Dock 4 reopened on May 14 after repairs were completed.','Restricted review: the cost of the May 12 disruption is not available to ordinary case readers.'];
let state={done:[],answers:{},lesson:1,capstone:[],notes:''};try{state={...state,...JSON.parse(localStorage.getItem('rag-fieldguide-v1')||'{}')}}catch{}
let lesson=Math.min(12,Math.max(1,Number(location.hash.match(/lesson-(\d+)/)?.[1])||state.lesson||1));let tab='learn';
function save(){state.lesson=lesson;try{localStorage.setItem('rag-fieldguide-v1',JSON.stringify(state))}catch{toast('Browser storage is unavailable. Progress lasts for this visit.')}}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',3000)}
function nav(){let h='';short.forEach((t,i)=>{if(i%2===0)h+=`<div class="nav-group">${groups[i/2]}</div>`;h+=`<button class="lesson-link ${lesson===i+1?'active':''}" data-lesson="${i+1}" ${lesson===i+1?'aria-current="step"':''}><span class="lesson-num">${state.done.includes(i+1)?'✓':String(i+1).padStart(2,'0')}</span>${t}</button>`});$('#lessons').innerHTML=h;$('#progress').value=state.done.length;$('#progress-label').textContent=`${state.done.length} of 12 lessons complete`;$('#lessons').querySelectorAll('button').forEach(b=>b.onclick=()=>go(+b.dataset.lesson));}
function go(n){lesson=n;tab='learn';location.hash=`lesson-${n}`;document.body.classList.remove('nav-open');$('#menu').setAttribute('aria-expanded','false');save();render();window.scrollTo({top:0,behavior:'instant'})}
function changeTab(t){tab=t;render()}
function render(){nav();document.title=`${short[lesson-1]} · RAG Fieldguide`;$('#title').textContent=titles[lesson-1];$('#intro').textContent=goals[lesson-1];$('#chapter-label').textContent=groups[Math.floor((lesson-1)/2)].split(' · ')[1];$('#lesson-count').textContent=`LESSON ${String(lesson).padStart(2,'0')} / 12`;$('#week-label').textContent=`Week ${String(Math.ceil(lesson/2)).padStart(2,'0')}`;document.querySelectorAll('[data-tab]').forEach(b=>{b.setAttribute('aria-selected',b.dataset.tab===tab);b.tabIndex=b.dataset.tab===tab?0:-1});$('#prev').disabled=lesson===1;$('#next').textContent=lesson===12?'Course progress →':'Next lesson →';if(tab==='learn'){renderPracticalLesson()}else if(tab==='lab')renderLab();else renderQuiz();}
function labShell(title,desc,body){$('#panel').innerHTML=`<div class="lab"><div class="lab-head"><span class="eyebrow">LEARN BY DOING · ${String(lesson).padStart(2,'0')}</span><h2>${title}</h2><p>${desc}</p></div><div class="lab-body">${body}</div></div>`}
function foundationLab(){labShell('Find the complete evidence chain','What equipment problem led to Harbor’s May 12 delay? Select the records you need.',records.slice(0,7).map((r,i)=>`<label class="record"><span class="check-label"><input type="checkbox" value="${i}" name="evidence"><span><strong>C${i+1}</strong>${r}</span></span></label>`).join('')+'<button class="primary" id="evaluate">Check my evidence</button><div id="lab-feedback" aria-live="polite"></div>');$('#evaluate').onclick=()=>{const picked=[...document.querySelectorAll('[name=evidence]:checked')].map(e=>+e.value);const hit=[0,1,2].filter(i=>picked.includes(i)).length;$('#lab-feedback').innerHTML=`<div class="feedback ${hit===3?'good':'warn'}"><strong>${hit}/3 required sources found.</strong> ${hit===3?'C1 establishes the delay, C2 connects the dock to the crane, and C3 identifies the hydraulic leak.':'You need C1 → C2 → C3 to connect the delay to its equipment cause.'}${picked.some(i=>i>2)?' The other selected records do not establish this cause.':''}</div>`}}
function renderQuiz(){labShell('Checkpoint','Explain what supports the answer before marking the lesson complete.','<p>Read the checkpoint in the lesson, then compare your answer with the full course answer key.</p>')}
$('#prev').onclick=()=>lesson>1&&go(lesson-1);$('#next').onclick=()=>lesson<12?go(lesson+1):changeTab('quiz');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>changeTab(b.dataset.tab));$('.tabs').addEventListener('keydown',e=>{const names=['learn','lab','quiz'];if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();changeTab(names[(names.indexOf(tab)+(e.key==='ArrowRight'?1:2))%3]);$(`[data-tab=${tab}]`).focus()}});$('#case-records').innerHTML=records.map((r,i)=>`<div class="record ${i===7?'disabled':''}"><strong>C${i+1}</strong>${r}</div>`).join('');$('#case-toggle').onclick=()=>$('#case-dialog').showModal();$('#case-close').onclick=()=>$('#case-dialog').close();$('#case-dialog').onclick=e=>{if(e.target===$('#case-dialog'))$('#case-dialog').close()};$('#menu').onclick=()=>{const open=document.body.classList.toggle('nav-open');$('#menu').setAttribute('aria-expanded',open)};document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.body.classList.remove('nav-open');$('#menu').setAttribute('aria-expanded','false')}});window.addEventListener('hashchange',()=>{const n=Number(location.hash.match(/lesson-(\d+)/)?.[1]);if(n>=1&&n<=12&&n!==lesson)go(n)});render();
